name: Alire Test Workflow

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Clone den dependency
        run: git clone https://github.com/mosteo/den.git ../den

      - name: Clone simple_logging dependency
        run: git clone https://github.com/mosteo/simple_logging.git ../simple_logging

      - name: Clone cstrings dependency
        run: git clone https://github.com/mosteo/cstrings.git ../c_strings

      - name: Set up Alire
        uses: alire-project/setup-alire@v5
        with:
          version: nightly

      - name: Run tests
        run: alr test
